name: create-libraries

on:
  push:
    tags: ['*']
  pull_request:
    branches: [ main ]

jobs:
  create-libraries:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm ci
      
      - name: Create Libraries
        run: npm run create-libraries

      - name: Release (if tag)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/icon-libraries/**/*.xml
